- name: Demo on Play Level Varibles
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Load variable From file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Demo on Play Level Varibles
  hosts: all

  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
          URL: play.example.com

- name: Variables from Role
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample

## varible precedence frist precedence is command line varible
##command line variable
## task level
## var dir from role 
##variable from files
## play level varibles
## inventory varibles

- name: Demo on Register Variable
  hosts: all
  tasks:
    - name: Run uptime shell command
      ansible.builtin.shell:
      register: output
    - name: Print output
      ansible.bultin.debug:
        msg: "{{ output }}"
