- name: Demo on Play Level Varibles
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Load variable From file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: Demo on Play Level Varibles
  hosts: all

  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
          URL: play.example.com