- name: Demo on Play Level Varibles
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}



- name: Demo on Task Level Varibles
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}