- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Download Maven Dependencies
  ansible.builtin.shell: pip3.6 install -r requirments.txt
    args:
      chdir: /app

- name: Include Schema setup
   ansible.builtin.import_tasks:
     file: schema_setup.yml

- name: Include SystemD setup
   ansible.builtin.import_tasks:
     file: systemd_setup.yml